"""Generic trading signal research platform primitives."""

from quant_platform.backtest import (
    BacktestAttribution,
    BacktestAttributionBucket,
    BacktestEquityPoint,
    BacktestExecutionConfig,
    BacktestStateSnapshot,
    BacktestStep,
    BacktestTrade,
    EventDrivenBacktest,
    EventDrivenBacktestResult,
)
from quant_platform.core import AssetSpec, MarketSpec
from quant_platform.connectors import DataConnector, DataConnectorRegistry
from quant_platform.connectors_sqlite import SQLiteBarConnector, SQLiteConnectorError
from quant_platform.data import BarSeriesId, DerivativeSeriesId, ExternalMetricSeriesId, FeatureSeriesId
from quant_platform.delivery import (
    DeliveryPayload,
    DeliveryResult,
    EmailDeliveryChannel,
    InMemoryDeliveryChannel,
    PineGoldenVector,
    TelegramDeliveryChannel,
    WebhookDeliveryChannel,
    compare_pine_golden_vectors,
)
from quant_platform.features import (
    BollingerConfig,
    BollingerFeatureModule,
    DonchianConfig,
    DonchianFeatureModule,
    DerivativesFeatureConfig,
    DerivativesFeatureModule,
    ExternalMetricFeatureConfig,
    ExternalMetricFeatureModule,
    FeatureEngine,
    FeatureRunResult,
    FeatureStoreWriter,
    PriceActionFeatureModule,
    TechnicalIndicatorConfig,
    TechnicalIndicatorModule,
    VolatilityConfig,
    VolatilityFeatureModule,
    VolumeConfig,
    VolumeFeatureModule,
    run_feature_engine_with_cache,
)
from quant_platform.markets import (
    MarketCatalog,
    default_crypto_market_catalog,
    load_market_catalog_json,
    save_market_catalog_json,
)
from quant_platform.regimes import (
    RegimeLabel,
    RegimeModel,
    RegimeProfile,
    RegimeProfileRegistry,
    load_regime_profile_registry_json,
)
from quant_platform.portfolio import (
    OrderAction,
    OrderStatus,
    PortfolioEngine,
    PortfolioOrder,
    PortfolioPlan,
    PortfolioState,
    Position,
    PositionKey,
)
from quant_platform.pipeline import PipelineResult, SignalPipeline
from quant_platform.risk import AccountState, RiskDecision, RiskEngine, RiskLimits, RiskState
from quant_platform.signal_modules import ColumnSignalConfig, ColumnSignalModule, SignalModule, SignalModuleRunner
from quant_platform.signals import Direction, Signal
from quant_platform.stores import (
    MissingStorageDependency,
    ParquetBarStore,
    ParquetDerivativeStore,
    ParquetExternalMetricStore,
    ParquetFeatureStore,
    SQLiteBarStore,
    SQLiteDerivativeStore,
    SQLiteExternalMetricStore,
    SQLiteFeatureStore,
)

__all__ = [
    "AssetSpec",
    "MarketSpec",
    "MarketCatalog",
    "default_crypto_market_catalog",
    "load_market_catalog_json",
    "save_market_catalog_json",
    "DataConnector",
    "DataConnectorRegistry",
    "SQLiteBarConnector",
    "SQLiteConnectorError",
    "BacktestAttribution",
    "BacktestAttributionBucket",
    "BacktestStep",
    "BacktestExecutionConfig",
    "BacktestEquityPoint",
    "BacktestStateSnapshot",
    "BacktestTrade",
    "EventDrivenBacktest",
    "EventDrivenBacktestResult",
    "BarSeriesId",
    "DerivativeSeriesId",
    "ExternalMetricSeriesId",
    "FeatureSeriesId",
    "DeliveryPayload",
    "DeliveryResult",
    "InMemoryDeliveryChannel",
    "WebhookDeliveryChannel",
    "TelegramDeliveryChannel",
    "EmailDeliveryChannel",
    "PineGoldenVector",
    "compare_pine_golden_vectors",
    "FeatureEngine",
    "FeatureRunResult",
    "FeatureStoreWriter",
    "run_feature_engine_with_cache",
    "TechnicalIndicatorConfig",
    "TechnicalIndicatorModule",
    "DonchianConfig",
    "DonchianFeatureModule",
    "DerivativesFeatureConfig",
    "DerivativesFeatureModule",
    "ExternalMetricFeatureConfig",
    "ExternalMetricFeatureModule",
    "VolumeConfig",
    "VolumeFeatureModule",
    "VolatilityConfig",
    "VolatilityFeatureModule",
    "BollingerConfig",
    "BollingerFeatureModule",
    "PriceActionFeatureModule",
    "RegimeLabel",
    "RegimeProfile",
    "RegimeProfileRegistry",
    "RegimeModel",
    "load_regime_profile_registry_json",
    "OrderAction",
    "OrderStatus",
    "PositionKey",
    "Position",
    "PortfolioState",
    "PortfolioOrder",
    "PortfolioPlan",
    "PortfolioEngine",
    "PipelineResult",
    "SignalPipeline",
    "AccountState",
    "RiskLimits",
    "RiskDecision",
    "RiskState",
    "RiskEngine",
    "ColumnSignalConfig",
    "ColumnSignalModule",
    "SignalModule",
    "SignalModuleRunner",
    "Direction",
    "Signal",
    "MissingStorageDependency",
    "ParquetBarStore",
    "ParquetDerivativeStore",
    "ParquetExternalMetricStore",
    "ParquetFeatureStore",
    "SQLiteBarStore",
    "SQLiteDerivativeStore",
    "SQLiteExternalMetricStore",
    "SQLiteFeatureStore",
]
